amo         : inserted
amas        : inserted
ama         : inserted
amamos      : inserted
amais       : inserted
amam        : inserted
amava       : inserted
amavas      : inserted
amava       : repeated
amávamos    : inserted
amáveis     : inserted
amavam      : inserted
amei        : inserted
amaste      : inserted
amou        : inserted
amamos      : repeated
amastes     : inserted
amaram      : inserted
amara       : inserted
amaras      : inserted
amara       : repeated
amáramos    : inserted
amáreis     : inserted
amaram      : repeated
amarei      : inserted
amarás      : inserted
amará       : inserted
amaremos    : inserted
amareis     : inserted
amarão      : inserted
amaria      : inserted
amarias     : inserted
amaria      : repeated
amaríamos   : inserted
amaríeis    : inserted
amariam     : inserted
ame         : inserted
ames        : inserted
ame         : repeated
amemos      : inserted
ameis       : inserted
amem        : inserted
amasse      : inserted
amasses     : inserted
amasse      : repeated
amássemos   : inserted
amásseis    : inserted
amassem     : inserted
amar        : inserted
amares      : inserted
amar        : repeated
amarmos     : inserted
amardes     : inserted
amarem      : inserted
ama         : repeated
ame         : repeated
amemos      : repeated
amai        : inserted
amem        : repeated
ames        : repeated
ame         : repeated
amemos      : repeated
ameis       : repeated
amem        : repeated
amar        : repeated
amares      : repeated
amar        : repeated
amarmos     : repeated
amardes     : repeated
amarem      : repeated

47 words
87 letters
88 nodes

